
---
version: '3.7'
services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    networks: 
      - docknet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner-config:/etc/gitlab-runner
    depends_on:
      - gitlab

        
  gitlab:
    hostname: gitlab
    networks:
      - docknet
    image: store/gitlab/gitlab-ce:11.10.4-ce.0
    ports:
      - '1443:443'
      - '1480:80'
      - '1422:22'
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-log:/var/log/gitlab
      - gitlab-config:/etc/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab'
        # docker:
        #   image: docker:19.03.1-dind
        #   privileged: true
        #   ports:
        #     - 2376:2376
        #   networks: 
        #     - docknet
        #   volumes:
        #     - certs-ca:/certs/ca
        #     - certs-client:/certs/client
        #   environment:
        #     - DOCKER_TLS_CERTDIR=/certs
    

networks:
  docknet:
    driver: bridge

volumes:
  certs-ca:
  certs-client:
  gitlab-runner-config:
  gitlab-config:
  gitlab-data:
  gitlab-log:
