stages: 
  - build
  - post-build
  - test


variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  # DOCKER_HOST: tcp://docker:2376
  # DOCKER_TLS_CERTDIR: "/certs"

build:gradle:
  image: gradle:jdk13
  stage: build
  script:
    - gradle -g "$CI_PROJECT_DIR/gradle-cache" build
  artifacts:
    paths:
      - build/libs/demo-0.0.1-SNAPSHOT.jar
    untracked: false
    expire_in: 30 days
  cache:
    key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
    paths:
      - gradle-cache/

build:docker:
  services:
    - postgres:latest
    - name: docker:19.03.1-dind
      alias: dind
  image: docker:19.03.1
  stage: post-build
  script:
    - DOCKER_HOST=$(hostname -i) docker build -f src/main/docker/Dockerfile build/libs -t demo
    - DOCKER_HOST=$(hostname -i) docker image save -o image.tar demo:latest 
    - gzip image.tar
    - ls
  artifacts:
    paths:
      - image.tar.gz
    untracked: false
    expire_in: 30 days
  dependencies:
    - build:gradle
